name: Actions Workflow
on: [push]
jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name : List Files in the directory 
        run: |
          pwd
          ls
      - name: Simple Javascript Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Mohamed Ali
      - name: log greating time
        run: echo "${{ steps.greet.outputs.time }}" 