name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hellow World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: multiple linkes
        run: |
          import platform
          print
          (platform.processor())
        shell: python
      